### ISSUE TITLE
Sample code compiled error

### ISSUE THREAD

**Issue by FloodShao** [streamjoin/nusthesis#11]
Environment:
* MacOS 10.15
* Sublime Text 3 + Mactex + skim
* I also tried the bash command, however, the compiler shows the same issue

Sample code Compiled error:
1. main.tex line47. \printbibliography undefined control sequence
2. ap-publication.tex line22. \printbibliography undefined control sequence
3. /usr/local/texlive/2016/texmf-dist/tex/latex/biblatex/biblatex.sty:11963: Package keyval Error: dashed undefined. [\blx@processoptions]

Solution:
Error 1. and 2.  According to <https://www.overleaf.com/learn/latex/Bibliography_management_with_biblatex>, you should include the following packages in the _global_settings.tex:
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
\usepackage{csquotes}

Error 3. The arg 'dashed' in _global_settings.tex {biblatex} is undefined, so I just comment it. 

If you are experiencing the same issue, you can try the aforementioned solutions.

**Comment by streamjoin** [comment]
Thanks for pointing out such compilation compatibility issues. Fixes for Error 1&2 have been incorporated in Commit 721a5ad4aac4f27aeab40d535ea6d3ed95e35a25. 

For Error 3, `dashed` is in fact necessary and not recommended to be dropped. It is undefined in ancient version of biblatex. Notice that you're using TeX Live 2016---better to upgrade it to avoid errors due to obsolete packages.
