### ISSUE TITLE
abstract to summary

### ISSUE THREAD

**Issue by xiazhiwang** [streamjoin/nusthesis#13]
Thanks for your template! 
I want to change the abstract to summary, but failed. I saw your comments “\renewcommand{\abstractname}{Summary}”, but still not success by using it.
Can you help me on this?

**Comment by streamjoin** [comment]
According to the discussion shown in the link below, this issue is caused by the the use of the `babel` package. 

https://tex.stackexchange.com/a/24778

I have fixed it in the commit 4d38c4f1abd29b95dbc618779f5b37d11d15cc86. Now you can uncomment the following line to change "Abstract" to "Summary". 

https://github.com/streamjoin/nusthesis/blob/4d38c4f1abd29b95dbc618779f5b37d11d15cc86/_global_settings.tex#L16

**Comment by xiazhiwang** [comment]
Thanks a lot!
