### ISSUE TITLE
Delete everything in my onedrive folder !!!

### ISSUE THREAD

**Issue by yangyang-nus-lv** [streamjoin/nusthesis#5]
I run .bat but there exist some error. Your code couldn't recognize the path name and save all temporary files in my onedrive root path. Then all my other file was deleted along with the temporary files. It caused me huge trouble! Please fix it.

**Comment by streamjoin** [comment]
I can't reproduce the defect under my environment. Could you provide the screen output for the issue? The .bat script will remove the temporary `pdfbuild` folder at the end. But it's quite weird that such newly created folder is redirected to your onedrive root path. 

Sorry for the inconvenience caused. I'm trying to improve the robustness of the script by adding sanity check to avoid similar issue.

**Comment by streamjoin** [comment]
I have removed the crappy `build.bat` script in the commit 6c6994be9153f9221b8cea4e3bc9db545120f5b9. This is mainly due to the fact that [Windows 10 already provides built-in Linux Bash Shell](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/). Therefore, it's recommended to run the `build.sh` script for compilation, which is much more robust.
