### ISSUE TITLE
Set DoubleSpacing for main text

### ISSUE THREAD

**Issue by YusongLeng** [streamjoin/nusthesis#9]
Hi,

Thanks again for your great work!

I encountered a problem with the line spacing. The 7th line of **_global_setings.tex** declares the double spacing by `\dsp`. But I'm confused by its comments saying that it is pseudo double space. And the compiled file is indeed double spaced.

> \dsp % pseudo double spacing

The thing is I would like to set the real double spacing for the main text. Could you please give me a hand on this? Thank you very much!

**Comment by YusongLeng** [comment]
Never mind. I figured out. This can be done by just set a correct value at the 138th line of nusthesis.cls

`\newcommand\dsp{\setSpacing{value}} % value is the one you set`  

The original value here is 1.37 that may stand for the single spacing. That why `/dsp` is commented as pseudo double spacing.

**Comment by streamjoin** [comment]
By setting `\dsp` to 2, it actually results in line spacing larger than double. The value of 1.37 is in fact fine-tuned for real double spacing in the eventual output. The comment saying "pseudo" may be confusing. The rationale behind is that the double line spacing is actualized by setting the specific space size between lines, rather than setting the line space itself.
